#!/bin/bash

# simple scripts for move window on another workspace (with xdotool, xwininfo)
# created by diws inspired by Graham

windowid=$(xdotool click 1 | xwininfo | awk NR==6'{print$4}')
vdesk 5 ${windowid}

notify-send 'Move to' 'workspace 5'
